# **Feature Engineering**
Although there is no universally preferred feature engineering method or pipeline, there are a handful of common tasks used to create features from different data types for different models.

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats

In [3]:
#sample dataset
data = {
    "Area": [1000, 1500, 2000, 1200, 1800],
    "Bedrooms": [2, 3, 4, 2, 3],
    "Year_Built": [2010, 2020, 2005, 2015, 2018],
    "Location": ["Kathmandu", "Pokhara", "Kathmandu",
                 "Lalitpur", "Pokhara"],
    "Price": [50, 80, 100, 60, 90]
}

df = pd.DataFrame(data)
df

   Area  Bedrooms  Year_Built   Location  Price
0  1000         2        2010  Kathmandu     50
1  1500         3        2020    Pokhara     80
2  2000         4        2005  Kathmandu    100
3  1200         2        2015   Lalitpur     60
4  1800         3        2018    Pokhara     90

## **Feature Creation**
Creating a new feature from existing features.

In [4]:
#creating a new feature "House Age"
df["House_Age"] = 2026 - df["Year_Built"]
df

   Area  Bedrooms  Year_Built   Location  Price  House_Age
0  1000         2        2010  Kathmandu     50         16
1  1500         3        2020    Pokhara     80          6
2  2000         4        2005  Kathmandu    100         21
3  1200         2        2015   Lalitpur     60         11
4  1800         3        2018    Pokhara     90          8

## **Feature Transformation and Scaling**
Changing the representation or scale of existing features to make them more suitable for a machine learning algorithm.Common techniques include:
- **Normalization:** Scales values to a fixed range, often 0 to 1.
- **Standardization:** Transforms values to have a mean of 0 and standard deviation of 1.
- **Log transformation:** Reduces skewness in highly skewed numerical data.
- **Binning:** This technique essentially transforms continuous, numerical values into categorical features
- **Encoding Categorical Features:** Representing the categorical features numerically. Using techniques like One-hot Encoding and Label Encoding

Most of these can be as a part of Data Cleaning and Preprocessing also

In [5]:
#sample data
df = pd.DataFrame({
    "Marks": [25, 38, 45, 56, 67, 74, 88, 95]
})

# Define bins and their labels
bins = [0, 40, 60, 80, 100]
labels = ["Low", "Medium", "High", "Very High"]

# Perform binning
df["Grade_Category"] = pd.cut(
    df["Marks"],
    bins=bins,
    labels=labels,
    include_lowest=True
)

df

   Marks Grade_Category
0     25            Low
1     38            Low
2     45         Medium
3     56         Medium
4     67           High
5     74           High
6     88      Very High
7     95      Very High

The intervals are:
- Low: 0–40
- Medium: above 40–60
- High: above 60–80
- Very High: above 80–100

## **Feature selection**
Feature selection involves choosing a subset of relevant features to use:

- **Filter methods:** Based on statistical measures like correlation.
- **Wrapper methods:** Select based on model performance.
- **Embedded methods:** Feature selection integrated within model training.

## **Feature Extraction**
Feature extraction means deriving meaningful information from raw or complex data and representing it as features.

Examples:
- Date and time: Extract day, month, year, or hour.
- Text: Convert descriptions into numerical vectors using TF-IDF.
- Images: Extract useful visual representations such as edges, shapes, or learned image features.

Some techniques include
- **Dimensionality reduction:** Techniques like PCA reduce features while preserving important information.
- **Aggregation & Combination:** Summing or averaging features to simplify the model.
- **Term Frequency-Inverse Document Frequency (TF-IDF):** Adjusts word importance based on frequency in a specific document compared to all documents, highlighting unique terms.